base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
]

umnombo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return f"{self.name}"

base/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

base/views.py
from django.shortcuts import render, redirect
from .models import Contact


# Create your views here.
def index(request):
    if request.method == 'POST':
        name = request.POST.get('name', "")
        email = request.POST.get('email', "")
        message = request.POST.get('message', "")
        user = Contact.objects.create(name=name, email=email, message=message)
        user.save()
        return redirect('/')
    return render(request, 'base/main.html')

def profile(request):
    return render(request, 'base/profile.html')

def services(request):
    return render(request, 'base/services.html')

def contact(request):
    return render(request, 'base/contact.html')

base/templates/base/contact.html
<!-- {% extends 'base/core.html' %}



{% block title %}Contact | Umnombo Wezolimo{% endblock %}

{% block body %} -->
    <!-- <h1 class="text-xl" bg-black>Contact</h1>

    <form method="post" action="">
        {% csrf_token %}
        

        <input type="submit" value="save">

    </form> -->


<!-- contact section -->
<!-- <section id="contact" class="contact section-padding">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="section-header text-center pb-5">

          <h2>Contact</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa at dolorem illum, aut vero voluptates adipisci necessitatibus. Numquam non mollitia, 
            voluptatum nobis quaerat rerum? Ut voluptatum atque libero laborum quos.</p>
          </div>
        </div>
    </div>

    <div class="row m-0">
      <div class="col-md-12 p-0 pt-4 p-4">
        <form action="" method="post" class="bg-light p-4.m-auto">
          <div class="row">
            <div class="col-md-12">
              <div class="mb-3">
                <input type="text" class="form-control" required placeholder="Your Full name">
              </div>
            </div>

            <div class="col-md-12">
              <div class="mb-3">
                <input type="email" class="form-control" required placeholder="Your Full email">
              </div>
            </div>

            <div class="col-md-12">
              <div class="mb-3">
                <textarea rows="3" required class="form-control" placeholder="Message"></textarea>
              </div>
            </div>
            <button class="btn btn-warning btn-lg btn-block mt-3">Send Now</button>
          </div>

        </form>
      </div>
    </div>
  </div>

</section>
{% endblock %} -->

base/templates/base/core.html
<!-- {% load static %}
    <!doctype html>
    <html lang="en">
        <head>
            
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Umnombo Wezolimo</title>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" 
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static '/css/styles.css' %}">
        </head>
        <body>
          {% include 'base/navbar.html' %}

          {% block body %}
          {% endblock body %}

          {% include 'base/footer.html' %}


          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
      </body>
  </html> -->

base/templates/base/footer.html
<footer class="bg-dark p-2 text-center">
    <div class="container">
      <p class="text-white">All Right Reserved @website kgafa tech</p>
    </div>
  </footer>

base/templates/base/navbar.html
<nav class="navbar navbar-expand-lg bg-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'base:index' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:services' %}">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:contact' %}">Contact</a>
          </li>
        </ul>
        
      </div>
    </div>
  </nav>  

base/templates/base/profile.html
{% extends 'base/core.html' %}
{% load static %}

{% block title %}Profile | Umnombo Wezolimo{% endblock %}

{% block body %}
  
    <section id="portfolio" class="portfolio section-padding">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="section-header text-center pb-5">
                <h2>Our Project</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa at dolorem illum, aut vero voluptates adipisci necessitatibus. Numquam non mollitia, 
                  voluptatum nobis quaerat rerum? Ut voluptatum atque libero laborum quos.</p>
                </div>
              </div>
              </div>
              <div class="row">
                <div class="col-12 col-md-12 col-lg-4">
                  <div class="card text-center bg-white pb-2">
                    <div class="card-body text-dark">
                      <div class="img-area mb-4">
                        <img src="{% static 'images/clean.JPG' %}" alt="" class="img-fluid">
                      </div>
                      <h3 class="card-title">Building Maker</h3>
                      <p class="lead">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Provident pariatur fugiat voluptatum autem perferendis, dolores, placeat earum ab sed iusto sapiente, 
                        reiciendis voluptatem! Culpa maiores at repudiandae, nulla dignissimos a!</p>
                        <button class="btn bg-warning text-dark">Learn More</button>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-md-12 col-lg-4">
                  <div class="card text-center bg-white pb-2">
                    <div class="card-body text-dark">
                      <div class="img-area mb-4">
                        <img src="{% static 'images/clean.JPG' %}" alt="" class="img-fluid">
                      </div>
                      <h3 class="card-title">Building Maker</h3>
                      <p class="lead">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Provident pariatur fugiat voluptatum autem perferendis, dolores, placeat earum ab sed iusto sapiente, 
                        reiciendis voluptatem! Culpa maiores at repudiandae, nulla dignissimos a!</p>
                        <button class="btn bg-warning text-dark">Learn More</button>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-md-12 col-lg-4">
                  <div class="card text-center bg-white pb-2">
                    <div class="card-body text-dark">
                      <div class="img-area mb-4">
                        <img src="{% static 'images/clean.JPG' %}" alt="" class="img-fluid">
                      </div>
                      <h3 class="card-title">Building Maker</h3>
                      <p class="lead">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Provident pariatur fugiat voluptatum autem perferendis, dolores, placeat earum ab sed iusto sapiente, 
                        reiciendis voluptatem! Culpa maiores at repudiandae, nulla dignissimos a!</p>
                        <button class="btn bg-warning text-dark">Learn More</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>

      </section>

      <section id="team" class="team section-padding">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="section-header text-center pb-5">
                <h2>Our Project</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa at dolorem illum, aut vero voluptates adipisci necessitatibus. Numquam non mollitia, 
                  voluptatum nobis quaerat rerum? Ut voluptatum atque libero laborum quos.</p>
                </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12 col-md-6 col-lg-3">
                  <div class="card text-center">
                    <div class="card-body">
                      <img src="{% static 'images/recent.JPG' %}" alt="" class="img-fluid rounded-circle">
                      <h3 class="card-title py-2">Thami Mbodla</h3>
                      <p class="card-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil praesentium magni odit quos nesciunt. Quos amet esse, iure quis maiores cum laboriosam adipisci pariatur, corrupti, 
                        reprehenderit delectus aspernatur maxime dignissimos!</p>

                        <p class="socials">
                          <i class="bi bi-twitter text-dark mx-1"></i>
                          <i class="bi bi-facebook text-dark mx-1"></i>
                          <i class="bi bi-linkedin text-dark mx-1"></i>
                          <i class="bi bi-instagram text-dark mx-1"></i>
                        </p>
                    </div>
                  </div>
                </div>
              </div>
              
        </div>
      </section>
{% endblock body %}

base/templates/base/services.html
{% extends 'base/core.html' %}

{% block title %}Services | Umnombo Wezolimo{% endblock %}

{% block body %}
    <section id="services" class="services section padding">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="section-header text-center pb-5">
                <h2>Our Services</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa at dolorem illum, aut vero voluptates adipisci necessitatibus. Numquam non mollitia, 
                  voluptatum nobis quaerat rerum? Ut voluptatum atque libero laborum quos.</p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-4">
              <div class="card text-white text-center bg-dark pb-2">
                <div class="card-body">
                  <i class="bi bi-subtract"></i>
                  <h3 class="card-title">Best Qaulity</h3>
                  <p class="lead">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas similique exercitationem, molestias aliquid deleniti sit. Maiores est nemo voluptates ipsum, 
                    quasi eveniet harum possimus, minima omnis unde magnam beatae. Minima.</p>
                    <button class="btn btn-warning text-dark">Read More</button>
                </div>
              </div>
            </div>
            <div class="col-12 col-md-12 col-lg-4">
              <div class="card text-white text-center bg-dark pb-2">
                <div class="card-body">
                  <i class="bi bi-twitter"></i>
                  <h3 class="card-title">Sustainability</h3>
                  <p class="lead">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas similique exercitationem, molestias aliquid deleniti sit. Maiores est nemo voluptates ipsum, 
                    quasi eveniet harum possimus, minima omnis unde magnam beatae. Minima.</p>
                    <button class="btn btn-warning text-dark">Read More</button>
                </div>
              </div>
            </div>
            <div class="col-12 col-md-12 col-lg-4">
              <div class="card text-white text-center bg-dark pb-2">
                <div class="card-body">
                  <i class="bi bi-telephone"></i>
                  <h3 class="card-title">Find Us</h3>
                  <p class="lead">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas similique exercitationem, molestias aliquid deleniti sit. Maiores est nemo voluptates ipsum, 
                    quasi eveniet harum possimus, minima omnis unde magnam beatae. Minima.</p>
                    <button class="btn btn-warning text-dark">Read More</button>
                </div>
              </div>
            </div>
          </div>

        </div>

      </section>
{% endblock body %}